<?php

/**
 * Implements hook_menu().
 */
function upitt_dashboard_menu() {
  $items = array(
    'admin/islandora/tools/upitt_dashboard' => array(
      'title' => 'University of Pittsburgh Admin Dashboard',
      'description' => 'Configure options related to the Admin Dashboard.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('upitt_dashboard_admin_form'),
      'access arguments' => array(UPITT_ISLANDORA_MEMBEROFSITE_MANAGE),
      'file' => 'includes/admin.form.inc',
    ),
  );

  return $items;
}

